EMAIL = 'build.bid.co@gmail.com'
PASSWORD = 'osgujxecoypjmkup'
SECRET_KEY = 'IUQTIM3WM5BHU2JDONHGY6Z7PNAF4XR6'
ADMIN_PASSWORD = 'buildbid.1234'
PRICE_RECORD_ID = '648f1ae1575886f0aa23b90f'

module.exports = {
  EMAIL,
  PASSWORD,
  SECRET_KEY,
  ADMIN_PASSWORD,
  PRICE_RECORD_ID
}
